- nextcloud2/app.cfg
myapp
> i.e. the folder of the app
My App
> i.e. the name appears on AppStore
Hello world
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> Optional
> Only need for first time submission of an app
> [Update][nextcloud2]for layout test

- nextcloud2/app.cfg
nextcloud2
Next Cloud2 for test
> [Update][nextcloud2] add more spec

- calendar/.helmignore
- calendar/Chart.yaml
- calendar/app.cfg
- calendar/templates/_helpers.tpl
- calendar/templates/calendar_deploy.yaml
- calendar/values.yaml
> e.g
calendar
Calendar
Calendar
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [NEW][calendar][0.0.1]add calendar

- nostream/.helmignore
- nostream/Chart.yaml
- nostream/app.cfg
- nostream/templates/_helpers.tpl
- nostream/templates/deployment.yaml
- nostream/values.yaml
> e.g
nostream
Nostream
A Nostr Relay written in TypeScript.
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [NEW][nostream][0.0.1]add nostream

- nextcloud2/Chart.yaml
- nextcloud2/app.cfg
- nextcloud2/index0.json
> e.g
nextcloud2
nextcloud2
nextcloud2
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud2][0.0.6]test

- sdwebui/Chart.yaml
- sdwebui/app.cfg
> e.g
sdwebui
sdwebui
Stable Diffusion web UI.
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][sdwebui][0.0.2] change sdwebui requiredGpu: 8Gi

- openllm/Chart.yaml
- openllm/app.cfg
- openllm/templates/deployment.yaml
- openllm/templates/traefik.yaml
openllm
openllm
OpenLLM is an open-source platform designed to facilitate the deployment and operation of large language models (LLMs) in real-world applications. With OpenLLM, you can run inference on any open-source LLM, deploy them on the cloud or on-premises, and build powerful AI applications.
Code：https://github.com/bentoml/OpenLLM
> [NEW][openllm][0.0.6]

- nocodb/Chart.yaml
- nocodb/app.cfg
> e.g
nocodb
Nocodb
add permission
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nocodb][0.0.2] add permission

- nocodb/Chart.yaml
- nocodb/app.cfg
> e.g
nocodb
Nocodb
update entrance.name to nocodb-svc
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nocodb][0.0.3] update entrance.name to nocodb-svc

- nextcloud2/Chart.yaml
- nextcloud2/app.cfg
> e.g
nextcloud2
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud2][0.0.7] test

- nextcloud2/Chart.yaml
- nextcloud2/app.cfg
> e.g
nextcloud2
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud2][0.0.8] test

- astral2/.helmignore
- astral2/Chart.yaml
- astral2/app.cfg
- astral2/templates/_helpers.tpl
- astral2/templates/deployment.yaml
- astral2/values.yaml
> e.g
astral2
astral2
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [NEW][astral2][0.0.1]for test

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.2] test

- astral2/Chart.yaml
- astral2/app.cfg
- astral2/templates/deployment.yaml
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.3] test

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.4] test

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.5] test

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.6] test

- n8n/templates/n8n.yaml
n8n
n8n
fix n8n mkdir permission denied
> [UPDATE][n8n][0.0.1] fix n8n mkdir permission denied

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.7]test update

- nextcloud2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud2][0.0.8]multi line description

- nextcloud2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud2][0.0.8]test description

- openllm/Chart.yaml
- openllm/app.cfg
- openllm/templates/deployment.yaml
- openllm/templates/traefik.yaml
openllm
openllm
fix ingress config
traefik ClusterRole -> Role
> [UPDATE][openllm][0.0.10]fix ingress

- showdoc/templates/showdoc.yaml
showdoc
showdoc
Directory -> DirectoryOrCreate
> [UPDATE][showdoc][0.0.1]Directory -> DirectoryOrCreate

- nextcloud2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud2][0.0.8]test new app.cfg

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.8]test

- nextcloud/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][nextcloud][0.0.2]fix depend

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.9]for test

- devbox/Chart.yaml
- devbox/app.cfg
- devbox/templates/deployment.yaml
devbox
DevBox
upgrade the image version to add some new features
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][devbox][0.1.1]devbox

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.11]for test

- astral2/Chart.yaml
- astral2/app.cfg
> e.g
myapp
My App
> Optional
Website：
Developer：
Submitter：
Lisence：
Contact Info：
> [UPDATE][astral2][0.0.12]for test

- astral2/Chart.yaml
- astral2/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][astral2][0.0.13]for test

- astral2/Chart.yaml
- astral2/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][astral2][0.0.14]for test

- devbox/Chart.yaml
- devbox/app.cfg
- devbox/templates/deployment.yaml
DevBox
add some help docs
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][devbox][0.1.2]devbox

- denostr/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> fix:modify denostr title

- nextcloud/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][nextcloud][0.0.2]OtherContent

- openllm/app.cfg
- sdwebui/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> fix:update gpu to 10Gi

- firefoxm/.helmignore
- firefoxm/Chart.yaml
- firefoxm/app.cfg
- firefoxm/templates/firefox.yaml
> 
> 
> 
> 
firefoxm
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [NEW][firefoxm][0.0.1] for test multi entrance

- devbox/Chart.yaml
- devbox/app.cfg
- devbox/templates/deployment.yaml
DevBox
upgrade theforce cli
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][devbox][0.1.3]devbox

- devbox/app.cfg
> 
> 
> 
> 
>
fix: update dependencies terminus.version for devbox
> Optional
- Website:
- Developer:
- Submitter:
- License:
> fix: update dependencies terminus.version

- homeassistant/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> fix: update homeassistant categories

- nextcloud/Chart.yaml
- nextcloud/app.cfg
- nextcloud/index0.json
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> fix: add index for nextcloud

- astral3/.helmignore
- astral3/Chart.yaml
- astral3/app.cfg
- astral3/owners
- astral3/templates/_helpers.tpl
- astral3/templates/deployment.yaml
- astral3/values.yaml
test3
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [NEW][astral3][0.0.14]test

- astral3/Chart.yaml
- astral3/app.cfg
> 
> > [UPDATE][foldername][version]OtherContent
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][astral3][0.0.15]OtherContent

- astral2/Chart.yaml
- astral2/app.cfg
- astral2/templates/deployment.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][astral2][0.0.16]for test

- astral5/.helmignore
- astral5/Chart.yaml
- astral5/app.cfg
- astral5/owners
- astral5/templates/_helpers.tpl
- astral5/templates/deployment.yaml
- astral5/values.yaml
- values.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [NEW][astral5][0.0.1]OtherContent

- astral5/Chart.yaml
- astral5/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][astral5][0.0.2]test001

- bazarr/Chart.yaml
- bazarr/app.cfg
- bazarr/templates/deployment.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][bazarr][0.0.2]test app.cfg

- openllm/app.cfg
- openllm/templates/deployment.yaml
- openllm/templates/traefik.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> Fix openllm

- sdwebui/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> add description for sd webui

- nextcloud/Chart.yaml
- nextcloud/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][nextcloud][0.0.4]add entranceName

- sdwebui/app.cfg
- sdwebui/templates/deployment.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> Update sd resource requirement

- codeserver/app.cfg
- geth/app.cfg
- homeassistant/app.cfg
- mastodon/app.cfg
- n8n/app.cfg
- nocodb/app.cfg
- photoprism/app.cfg
- photoview/app.cfg
- sdwebui/app.cfg
- showdoc/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> fix:update some png to webp

- gitlabfusion/Chart.yaml
- gitlabfusion/app.cfg
- gitlabfusion/owners
- gitlabfusion/templates/clientproxy.yaml
- gitlabfusion/templates/gitlab.yaml
- gitlabfusion/templates/serverproxy.yaml
App Title
Gitlabfusion
Description
terminus account + gitlab
Statement
[x]I have tested the app to ensure it is compatible with the Terminus OS version stated in the app.cfg file
[x] I guarantee that this submission adheres to the community rules
> [NEW][gitlabfusion][0.0.91]Gitlabfusion

- gitlabpure/Chart.yaml
- gitlabpure/app.cfg
- gitlabpure/owners
- gitlabpure/templates/gitlab.yaml
Gitlabpure
Pure version of gitlab
> [NEW][gitlabpure][0.0.45]Gitlabpure

- nocodb/app.cfg
- nocodb/owners
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][nocodb][0.0.3]update description

- nocodb/Chart.yaml
- nocodb/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][nocodb][0.0.5]add upgrade description

- gitlabfusion/templates/serverproxy.yaml
- gitlabfusionclient/Chart.yaml
- gitlabfusionclient/app.cfg
- gitlabfusionclient/templates/clientproxy.yaml
gitlabfusionclient
support  verify git cli by use system username and password
> [UPDATE][gitlabfusionclient][0.0.14]check system password

- gitlabfusion/Chart.yaml
- gitlabfusion/app.cfg
- gitlabfusion/templates/serverproxy.yaml
gitlabfusion
fix server proxy port config
> [UPDATE][gitlabfusion][0.0.92]fix port

- mastodon/Chart.yaml
- mastodon/app.cfg
- mastodon/templates/all.yaml
> [UPDATE][mastodon][0.0.2]fix resources config

- comfyui/Chart.yaml
- comfyui/app.cfg
- comfyui/owners
- comfyui/templates/deployment.yaml
Comfyui
The most powerful and modular stable diffusion GUI and backend.
> [NEW][comfyui][0.0.9]Comfyui

- bytebase/Chart.yaml
- bytebase/app.cfg
- bytebase/owners
- bytebase/templates/bytebase.yaml
- bytebase/templates/proxy.yaml
Bytebase
Different database development tasks Multiple database systems Unified process Single tool
> [NEW][bytebase][0.0.21]bytebase

- bytebase/Chart.yaml
- bytebase/app.cfg
- bytebase/owners
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> Update bytebase 0.0.2

- mastodon/Chart.yaml
- mastodon/app.cfg
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][mastodon][0.0.3]add content

- bytebase/Chart.yaml
- bytebase/app.cfg
> [UPDATE][bytebase][0.0.3]Fix entrance name

- mastodon/Chart.yaml
- mastodon/app.cfg
> [UPDATE][mastodon][0.0.4]list mastodon

- homeassistant/Chart.yaml
- homeassistant/app.cfg
> [UPDATE][homeassistant][0.0.2]add info

- bytebase/Chart.yaml
- bytebase/app.cfg
- bytebase/templates/proxy.yaml
> [UPDATE][bytebase][0.0.4]fix password

- jellyfin/Chart.yaml
- jellyfin/app.cfg
> [UPDATE][jellyfin][0.0.2]update info

- nocodb/Chart.yaml
- nocodb/README.md
- nocodb/app.cfg
> [UPDATE][nocodb][0.0.6]fix icon & remove Readme

- comfyui/Chart.yaml
- comfyui/app.cfg
> [UPDATE][comfyui][0.0.11]fix icon

- gitlabfusion/Chart.yaml
- gitlabfusion/app.cfg
> [UPDATE][gitlabfusion][0.0.93]add info

- gitlabpure/Chart.yaml
- gitlabpure/app.cfg
> [UPDATE][gitlabpure][0.0.46]update info

- gitlabfusionclient/Chart.yaml
- gitlabfusionclient/app.cfg
- gitlabpure/app.cfg
> [UPDATE][gitlabfusionclient][0.0.15]update info

- photoprism/Chart.yaml
- photoprism/app.cfg
> [UPDATE][photoprism][0.0.2]add info

- geth/Chart.yaml
- geth/app.cfg
- geth/templates/geth.yaml
- geth/templates/traefik.yaml
- geth/templates/website.yaml
> [UPDATE][geth][0.0.2]add info

- wordpress/Chart.yaml
- wordpress/app.cfg
- wordpress/owners
- wordpress/templates/wordpress.yaml
Wordpress
WordPress is a very special project to me. Every developer and contributor adds something unique to the mix, and together we create something beautiful that I am proud to be a part of. Thousands of hours have gone into WordPress, and we are dedicated to making it better every day. Thank you for making it part of your world.
> [NEW][wordpress][0.0.2]new app wordpress

- n8n/Chart.yaml
- n8n/app.cfg
> [UPDATE][n8n][0.0.2]add info

- onlyoffice/.helmignore
- onlyoffice/Chart.yaml
- onlyoffice/app.cfg
- onlyoffice/owners
- onlyoffice/templates/_helpers.tpl
- onlyoffice/templates/deployment.yaml
- onlyoffice/values.yaml
OnlyOffice
ONLYOFFICE Docs is a free collaborative online office suite comprising viewers and editors for texts, spreadsheets and presentations, forms and PDF, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx and enabling collaborative editing in real time.
> [NEW][onlyoffice][0.0.1]add onlyoffice

- farcaster/Chart.yaml
- farcaster/app.cfg
> [UPDATE][farcaster][0.0.2]update info

- sealcaster/Chart.yaml
- sealcaster/app.cfg
> [UPDATE][sealcaster][0.0.2]add promote image and change icon

- nostream/Chart.yaml
- nostream/app.cfg
> [UPDATE][nostream][0.0.2]update info

- coracle/Chart.yaml
- element/Chart.yaml
- firefly/Chart.yaml
- joplin/Chart.yaml
- libreddit/Chart.yaml
- nodered/Chart.yaml
- plex/Chart.yaml
- primal/Chart.yaml
- snort/Chart.yaml
- synapse/Chart.yaml
- vaultwarden/Chart.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> Fix chartname

- coracle/Chart.yaml
- coracle/app.cfg
> [UPDATE][coracle][0.0.2]update info

- element/Chart.yaml
- element/app.cfg
> [UPDATE][element][0.0.2]update info

- joplin/Chart.yaml
- joplin/app.cfg
> [UPDATE][joplin][0.0.2]change icon

- snort/Chart.yaml
- snort/app.cfg
> [UPDATE][snort][0.0.2]change icon

- primal/Chart.yaml
- primal/app.cfg
> [UPDATE][primal][0.0.2]change icon

- plex/Chart.yaml
- plex/app.cfg
> [UPDATE][plex][0.0.2]change icon

- nodered/Chart.yaml
- nodered/app.cfg
> [UPDATE][nodered][0.0.2]change icon

- libreddit/Chart.yaml
- libreddit/app.cfg
> [UPDATE][libreddit][0.0.2]change icon

- vaultwarden/Chart.yaml
- vaultwarden/app.cfg
> [UPDATE][vaultwarden][0.0.2]change icon

- wordpress/Chart.yaml
- wordpress/app.cfg
- wordpress/templates/proxy.yaml
- wordpress/templates/wordpress.yaml
Wordpress
Support using system users to log in to the admin page
> [UPDATE][wordpress][0.0.3]wordpress add proxy

- comfyui/Chart.yaml
- comfyui/app.cfg
- comfyui/templates/deployment.yaml
> [UPDATE][comfyui][0.0.12]fix config namespace

- firefly/Chart.yaml
- firefly/app.cfg
> [UPDATE][firefly][0.0.2]OtherContent

- wordpress/Chart.yaml
- wordpress/app.cfg
- wordpress/templates/proxy.yaml
Wordpress
fix: open in desktop
> [UPDATE][wordpress][0.0.4] fix x-frame-options

- synapse/Chart.yaml
- synapse/app.cfg
> [UPDATE][synapse][0.0.2]update info and fix icon

- jellyfin/Chart.yaml
- jellyfin/app.cfg
> [UPDATE][jellyfin][0.0.3]add clients

- test/Chart.yaml
- test/app.cfg
- test/index0.json
- test/owners
- test/templates/gitlab.yaml
> [NEW][test][0.0.1]submit test app

- test/Chart.yaml
- test/app.cfg
> [UPDATE][test][0.0.2]add policy

- recommendtasken0/templates/recommend.yaml
- recommendtasken10800/templates/recommend.yaml
- recommendtasken10800/templates/train.yaml
- recommendtaskzhcn0/templates/recommend.yaml
- recommendtaskzhcn0/templates/train.yaml
- recommendtaskzhcn86400/templates/recommend.yaml
- recommendtaskzhcn86400/templates/train.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> recommend source

- recommendauto/owners
- recommendbaseball/owners
- recommendbasketball/owners
- recommendbusiness/owners
- recommenddigital/owners
- recommendf1/owners
- recommendfashion/owners
- recommendfood/owners
- recommendfootball/owners
- recommendgaming/owners
- recommendgeek/owners
- recommendgolf/owners
- recommendscience /owners
- recommendsoccer/owners
- recommendsports/owners
- recommendtechbusiness/owners
- recommendtechnews/owners
- recommendtennis/owners
- recommendtoutiao/owners
- recommendtvmovie/owners
- recommendworldnews/owners
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> add owner for recommends

- recommendtasken0/templates/recommend.yaml
- recommendtasken10800/templates/recommend.yaml
- recommendtasken10800/templates/train.yaml
- recommendtaskzhcn0/templates/recommend.yaml
- recommendtaskzhcn0/templates/train.yaml
- recommendtaskzhcn86400/templates/recommend.yaml
- recommendtaskzhcn86400/templates/train.yaml
- recommendworldnews/templates/embedding.yaml
- recommendworldnews/templates/recommend.yaml
- recommendworldnews/templates/train.yaml
- recommendzhcntech/.helmignore
- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/owners
- recommendzhcntech/templates/_helpers.tpl
- recommendzhcntech/templates/embedding.yaml
- recommendzhcntech/templates/recommend.yaml
- recommendzhcntech/templates/train.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [NEW][recommendzhcntech][0.0.1]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.0.2]bump version

- recommendzhcntech/Chart.yaml
- recommendzhcntech/README.md
- recommendzhcntech/app.cfg
- recommendzhcntech/owners
> [UPDATE][recommendzhcntech][0.0.2]fix chart

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
> [UPDATE][recommendzhcntech][0.0.4]bump version

- firefox/Chart.yaml
- firefox/app.cfg
- firefox/owners
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][firefox][0.0.3]update for test

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
- recommendworldnews/templates/embedding.yaml
- recommendworldnews/templates/recommend.yaml
- recommendworldnews/templates/train.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][recommendworldnews][0.1.2]

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/templates/embedding.yaml
- recommendzhcntech/templates/recommend.yaml
- recommendzhcntech/templates/train.yaml
> 
> 
> 
> 
>
> Optional
- Website:
- Developer:
- Submitter:
- License:
> [UPDATE][recommendzhcntech][0.1.2]

- wordpress/Chart.yaml
- wordpress/app.cfg
> [UPDATE][wordpress][0.0.5]update info

- astral/Chart.yaml
- astral/app.cfg
> [UPDATE][astral][0.0.2]bump version2

- comfyui/Chart.yaml
- comfyui/app.cfg
> [UPDATE][comfyui][0.0.13]fix CPU error

- qbittorrent/Chart.yaml
- qbittorrent/app.cfg
> [UPDATE][qbittorrent][0.0.2] update info

- dendrite/Chart.yaml
- dendrite/app.cfg
> [UPDATE][dendrite][0.0.2]fix denpendency

- gitlabfusionclient/Chart.yaml
- gitlabfusionclient/app.cfg
> [UPDATE][gitlabfusionclient][0.0.16]reduce cpu request

- photoview/Chart.yaml
- photoview/app.cfg
> [UPDATE][photoview][0.0.2]update info

- astral/Chart.yaml
- astral/app.cfg
> [UPDATE][astral][0.0.3]update info

- codeserver/Chart.yaml
- codeserver/app.cfg
> [UPDATE][codeserver][0.0.4]update info

- wordpress/Chart.yaml
- wordpress/app.cfg
> [UPDATE][wordpress][0.0.6]add policy

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.1.4]fix version name

- gitlabfusion/Chart.yaml
- gitlabfusion/app.cfg
- gitlabfusion/templates/clientproxy.yaml
- gitlabfusion/templates/serverproxy.yaml
Gitlabfusion
support login root
fix create account case in show verision update alert
> [UPDATE][gitlabfusion][0.0.94]support login root

- gitlabfusionclient/Chart.yaml
- gitlabfusionclient/app.cfg
- gitlabfusionclient/templates/clientproxy.yaml
Gitlab fusion client
create password on install app
> [UPDATE][gitlabfusionclient][0.0.17]create password on install app

- novella/Chart.yaml
- novella/app.cfg
- novella/owners
- novella/templates/deployment.yaml
Novella
Example Next.js application using [novel](https://github.com/steven-tey/novel).
> [NEW][novella][0.0.8]new app novella

- novella/Chart.yaml
- novella/app.cfg
novella
update short description
> [UPDATE][novella][0.0.9]Update description

- bytebase/Chart.yaml
- bytebase/app.cfg
> [UPDATE][bytebase][0.0.5]fix featured image

- novella/Chart.yaml
- novella/app.cfg
> [UPDATE][novella][0.0.10]update info

- recommendworldnews/Chart.yaml
- recommendworldnews/README.md
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.1.5]update reademe

- recommendzhcntech/Chart.yaml
- recommendzhcntech/README.md
- recommendzhcntech/app.cfg
> [UPDATE][recommendzhcntech][0.1.4]update md and version

- recommendworldnews/Chart.yaml
- recommendworldnews/README.md
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.1.6]fix md error

- novella/Chart.yaml
- novella/app.cfg
- novella/owners
- novella/templates/deployment.yaml
> [NEW][novella][0.0.11]add novella

- transmission/Chart.yaml
- transmission/app.cfg
> [UPDATE][transmission][0.0.2]update info

- showdoc/Chart.yaml
- showdoc/app.cfg
> [UPDATE][showdoc][0.0.2]update info

- n8n/Chart.yaml
- n8n/app.cfg
> [UPDATE][n8n][0.0.3]Fix featuredImage error

- radicale/Chart.yaml
- radicale/app.cfg
> [UPDATE][radicale][0.0.2]update description and add default credential

- photoprism/Chart.yaml
- photoprism/app.cfg
PhotoPrism
update default credentials
> [UPDATE][photoprism][0.0.4]update default credentials

- miniflux/Chart.yaml
- miniflux/app.cfg
- miniflux/templates/db-deployment.yaml
- miniflux/templates/miniflux-deployment.yaml
> [UPDATE][miniflux][0.0.2]update info and fix resource error

- deluge/Chart.yaml
- deluge/app.cfg
> [UPDATE][deluge][0.0.2]update info and add default password

- omnivore/Chart.yaml
- omnivore/app.cfg
> [UPDATE][omnivore][0.0.2]fix dependencies error

- miniflux/Chart.yaml
- miniflux/app.cfg
> [UPDATE][miniflux][0.0.3]add Default credentials and reduce cpu requirement

- nzbget/Chart.yaml
- nzbget/app.cfg
> [UPDATE][nzbget][0.0.3]bump version for test

- nzbget/Chart.yaml
- nzbget/app.cfg
> [UPDATE][nzbget][0.0.4]bump version for test

- nzbget/Chart.yaml
- nzbget/app.cfg
> [UPDATE][nzbget][0.0.5]bump version for test2

- denostr/Chart.yaml
- denostr/app.cfg
- denostr/templates/traefik.yaml
- denostr/templates/worker.yaml
> [UPDATE][denostr][0.0.17] fix denostr install

- prowlarr/Chart.yaml
- prowlarr/app.cfg
- prowlarr/templates/deployment.yaml
> [UPDATE][prowlarr][0.0.2]fix prowlarr install

- bazarr/Chart.yaml
- bazarr/app.cfg
- bazarr/owners
- bazarr/templates/deployment.yaml
> [UPDATE][bazarr][0.0.3]fix image

- readarr/Chart.yaml
- readarr/app.cfg
- readarr/owners
- readarr/templates/deployment.yaml
> [UPDATE][readarr][0.0.2]fix image

- radarr/Chart.yaml
- radarr/app.cfg
- radarr/owners
- radarr/templates/deployment.yaml
> [UPDATE][radarr][0.0.2]fix image

- nzbget/Chart.yaml
- nzbget/app.cfg
> [UPDATE][nzbget][0.0.6]bump version for test

- homeassistant/Chart.yaml
- homeassistant/app.cfg
> [UPDATE][homeassistant][0.0.14]fix featured image and title

- bytebase/Chart.yaml
- bytebase/app.cfg
- bytebase/templates/bytebase.yaml
> [UPDATE][bytebase][0.0.6]fix bytebase image

- recommendtest/.helmignore
- recommendtest/Chart.yaml
- recommendtest/README.md
- recommendtest/app.cfg
- recommendtest/owners
- recommendtest/templates/_helpers.tpl
- recommendtest/templates/embedding.yaml
- recommendtest/templates/recommend.yaml
- recommendtest/templates/train.yaml
- recommendtest/templates/workflow-controller-secrets.yaml
> [NEW][recommendtest][0.1.6]add recommend test

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/templates/recommend.yaml
recommend zhcn tech update to v0.1.5
>  [UPDATE][recommendzhcntech][0.1.5]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
- recommendworldnews/templates/recommend.yaml
update recommend worldnews to v0.1.7
> [UPDATE][recommendworldnews][0.1.7]

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/templates/recommend.yaml
>  [UPDATE][recommendzhcntech][0.1.6]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.1.8]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.1.9]

- recommendtest/Chart.yaml
- recommendtest/app.cfg
- recommendtest/templates/prerank.yaml
- recommendtest/templates/rank.yaml
> [UPDATE][recommendtest][0.1.11]

- recommendtest/Chart.yaml
- recommendtest/app.cfg
- recommendtest/templates/prerank.yaml
- recommendtest/templates/rank.yaml
- recommendtest/templates/train.yaml
> [UPDATE][recommendtest][0.1.12]

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/templates/prerank.yaml
> [UPDATE][recommendzhcntech][0.1.8]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
- recommendworldnews/templates/embedding.yaml
- recommendworldnews/templates/prerank.yaml
- recommendworldnews/templates/rank.yaml
> [UPDATE][recommendworldnews][0.1.11]

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/templates/prerank.yaml
- recommendzhcntech/templates/rank.yaml
> [UPDATE][recommendzhcntech][0.1.9]

- calibreweb/Chart.yaml
- calibreweb/app.cfg
> [UPDATE][calibreweb][0.0.2]add default credentials and description

- codeserver/Chart.yaml
- codeserver/app.cfg
> [UPDATE][codeserver][0.0.5]add default credentials

- gitlabpure/Chart.yaml
- gitlabpure/app.cfg
> [UPDATE][gitlabpure][0.0.47]add Default credentials

- recommendtest/Chart.yaml
- recommendtest/README.md
- recommendtest/app.cfg
> [UPDATE][recommendtest][0.1.14]Update README.md

- recommendtest/Chart.yaml
- recommendtest/README.md
- recommendtest/app.cfg
> [UPDATE][recommendtest][0.1.15]fix readme format

- recommendzhcntech/Chart.yaml
- recommendzhcntech/README.md
- recommendzhcntech/app.cfg
> [UPDATE][recommendzhcntech][0.1.11]update readme

- recommendworldnews/Chart.yaml
- recommendworldnews/README.md
- recommendworldnews/app.cfg
> [UPDATE][recommendworldnews][0.1.12]update readme

- radarr/Chart.yaml
- radarr/app.cfg
> [UPDATE][radarr][0.0.3]update info

- readarr/Chart.yaml
- readarr/app.cfg
> [UPDATE][readarr][0.0.3]update info

- prowlarr/Chart.yaml
- prowlarr/app.cfg
> [UPDATE][prowlarr][0.0.3]update info

- sonarr/Chart.yaml
- sonarr/app.cfg
> [UPDATE][sonarr][0.0.2]update info

- affine/Chart.yaml
- affine/app.cfg
- affine/owners
- affine/templates/deployment.yaml
> [NEW][affine][0.0.1]Add Affine Project

- obsidian/Chart.yaml
- obsidian/app.cfg
- obsidian/templates/deployment.yaml
> [UPDATE][obsidian][0.0.2]update info

- lidarr/Chart.yaml
- lidarr/app.cfg
> [UPDATE][lidarr][0.0.2]update info

- bazarr/Chart.yaml
- bazarr/app.cfg
> [UPDATE][bazarr][0.0.4]update info

- sickchill/Chart.yaml
- sickchill/app.cfg
> [UPDATE][sickchill][0.0.2]update info

- comfyui/Chart.yaml
- comfyui/app.cfg
> [UPDATE][comfyui][0.0.14]update info

- recommendt0327/.helmignore
- recommendt0327/Chart.yaml
- recommendt0327/README.md
- recommendt0327/app.cfg
- recommendt0327/owners
- recommendt0327/templates/_helpers.tpl
- recommendt0327/templates/embedding.yaml
- recommendt0327/templates/prerank.yaml
- recommendt0327/templates/rank.yaml
- recommendt0327/templates/train.yaml
Recommend Test 0327
Recommend for test
> [NEW][recommendt0327][0.0.1]add recommendt0327 for test

- recommendt0327/Chart.yaml
- recommendt0327/app.cfg
- recommendt0327/templates/embedding.yaml
- recommendt0327/templates/prerank.yaml
- recommendt0327/templates/rank.yaml
- recommendt0327/templates/train.yaml
> [UPDATE][recommendt0327][0.0.2]fix source name error

- recommendt0327/templates/train.yaml
- recommendtest/templates/train.yaml
- recommendworldnews/templates/train.yaml
- recommendzhcntech/templates/rank.yaml
- recommendzhcntech/templates/train.yaml
> update train and rank to latest 0.1.7

- affine/Chart.yaml
- affine/app.cfg
> [UPDATE][affine][0.0.2]

- navidrome/Chart.yaml
- navidrome/app.cfg
- navidrome/owners
- navidrome/templates/deployment.yaml
> [NEW][navidrome][0.0.1]

- ghost/Chart.yaml
- ghost/app.cfg
- ghost/owners
- ghost/templates/deployment.yaml
> [NEW][ghost][0.0.1]

- onlyoffice/Chart.yaml
- onlyoffice/app.cfg
- onlyoffice/owners
> [UPDATE][onlyoffice][0.0.2]Pengpeng patch 1

- showdoc/Chart.yaml
- showdoc/app.cfg
- showdoc/templates/showdoc.yaml
Showdoc
fix file access permissions
> [UPDATE][showdoc][0.0.4]fix file access permissions

- n8n/Chart.yaml
- n8n/app.cfg
- n8n/templates/n8n.yaml
> [UPDATE][n8n][0.0.6]fix config

- recommendzhcntech/Chart.yaml
- recommendzhcntech/app.cfg
- recommendzhcntech/templates/prerank.yaml
- recommendzhcntech/templates/rank.yaml
> [UPDATE][recommendzhcntech][0.1.15]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
- recommendworldnews/templates/prerank.yaml
- recommendworldnews/templates/rank.yaml
> [UPDATE][recommendworldnews][0.1.17]

- recommendworldnews/Chart.yaml
- recommendworldnews/app.cfg
- recommendworldnews/templates/prerank.yaml
- recommendworldnews/templates/rank.yaml
> [UPDATE][recommendworldnews][0.1.18]

- recommendworldnews/Chart.yaml
- recommendworldnews/TerminusManifest.yaml
- recommendworldnews/templates/embedding.yaml
- recommendworldnews/templates/rank.yaml
> [UPDATE][recommendworldnews][0.1.19]

- recommendtechnews/Chart.yaml
- recommendtechnews/TerminusManifest.yaml
- recommendtechnews/templates/prerank.yaml
- recommendtechnews/templates/rank.yaml
> [UPDATE][recommendtechnews][0.0.8]

- navidrome/Chart.yaml
- navidrome/TerminusManifest.yaml
- navidrome/owners
> [UPDATE][navidrome][0.0.2]fix version

- ghost/Chart.yaml
- ghost/TerminusManifest.yaml
> [UPDATE][ghost][0.0.2]fix version & change open method

- navidrome/Chart.yaml
- navidrome/TerminusManifest.yaml
> [UPDATE][navidrome][0.0.3]change open method

- llama2chat7bq4/.helmignore
- llama2chat7bq4/Chart.yaml
- llama2chat7bq4/README.md
- llama2chat7bq4/TerminusManifest.yaml
- llama2chat7bq4/modelConfig.yaml
- llama2chat7bq4/owners
> [NEW][llama2chat7bq4][0.0.1]add model llama2

- recommendzhcntech/Chart.yaml
- recommendzhcntech/TerminusManifest.yaml
> [UPDATE][recommendzhcntech][0.1.16]

- recommendworldnews/Chart.yaml
- recommendworldnews/TerminusManifest.yaml
- recommendworldnews/templates/prerank.yaml
- recommendworldnews/templates/rank.yaml
> [UPDATE][recommendworldnews][0.1.21]

- recommendzhcntech/Chart.yaml
- recommendzhcntech/TerminusManifest.yaml
- recommendzhcntech/templates/prerank.yaml
- recommendzhcntech/templates/rank.yaml
> [UPDATE][recommendzhcntech][0.1.19]

- mistralins7bq4/.helmignore
- mistralins7bq4/Chart.yaml
- mistralins7bq4/README.md
- mistralins7bq4/TerminusManifest.yaml
- mistralins7bq4/modelConfig.yaml
- mistralins7bq4/owners
>  [NEW][mistralins7bq4][0.0.1]add Mistral 7b

- r4sport/Chart.yaml
- r4sport/TerminusManifest.yaml
> [UPDATE][r4sport][0.1.22]fix title and categories

- r4tech/Chart.yaml
- r4tech/TerminusManifest.yaml
> [UPDATE][r4tech][0.0.9]

- r4entertainment/Chart.yaml
- r4entertainment/TerminusManifest.yaml
> [UPDATE][r4entertainment][0.1.22]fix feed provider and icon

- affine/Chart.yaml
- affine/TerminusManifest.yaml
- affine/owners
> [UPDATE][affine][version]update info & add owners

- affine/Chart.yaml
- affine/TerminusManifest.yaml
- affine/owners
> [UPDATE][affine][0.0.4]check chart 

- navidrome/Chart.yaml
- navidrome/TerminusManifest.yaml
> [UPDATE][navidrome][0.0.4]update spec info

- onlyoffice/Chart.yaml
- onlyoffice/TerminusManifest.yaml
> [UPDATE][onlyoffice][0.0.4]update detail

- onlyoffice/Chart.yaml
- onlyoffice/TerminusManifest.yaml
> [UPDATE][onlyoffice][0.0.5]fix system dependency

- llama2chat7bq4/Chart.yaml
- llama2chat7bq4/README.md
- llama2chat7bq4/TerminusManifest.yaml
> [UPDATE][llama2chat7bq4][0.0.2]test markdown

- openchat7b/Chart.yaml
- openchat7b/README.md
- openchat7b/TerminusManifest.yaml
>  [UPDATE][openchat7b][0.0.2]Update Readme & Description

- yarnmistral7b/Chart.yaml
- yarnmistral7b/README.md
- yarnmistral7b/TerminusManifest.yaml
> [UPDATE][yarnmistral7b][0.0.2]add README

- phi23b/Chart.yaml
- phi23b/README.md
- phi23b/TerminusManifest.yaml
> [UPDATE][phi23b][0.0.2]update readme

- noromaid7b/Chart.yaml
- noromaid7b/README.md
- noromaid7b/TerminusManifest.yaml
> [UPDATE][noromaid7b][0.0.2]update readme and some info

- phi23b/Chart.yaml
- phi23b/README.md
- phi23b/TerminusManifest.yaml
> [UPDATE][phi23b][0.0.3]fix chart version

- mistralins7bq4/Chart.yaml
- mistralins7bq4/README.md
- mistralins7bq4/TerminusManifest.yaml
> [UPDATE][mistralins7bq4][0.0.2]update info

- stealth7b/Chart.yaml
- stealth7b/README.md
- stealth7b/TerminusManifest.yaml
> [UPDATE][stealth7b][0.0.2]update README

- r4world/Chart.yaml
- r4world/README.md
- r4world/TerminusManifest.yaml
> [UPDATE][r4world][0.1.22]Update Readme

- r4world/Chart.yaml
- r4world/README.md
- r4world/TerminusManifest.yaml
> 
> [UPDATE][r4world][0.1.23]
> 
> 
> [UPDATE][r4world][0.1.23]Update r4world

- r4techbiz/Chart.yaml
- r4techbiz/README.md
- r4techbiz/TerminusManifest.yaml
> [UPDATE][r4techbiz][0.1.20]update description

- r4tech/Chart.yaml
- r4tech/README.md
- r4tech/TerminusManifest.yaml
> [UPDATE][r4tech][0.1.10]update readme

- r4sport/Chart.yaml
- r4sport/README.md
- r4sport/TerminusManifest.yaml
> [UPDATE][r4sport][0.1.23]Update readme

- r4business/Chart.yaml
- r4business/README.md
- r4business/TerminusManifest.yaml
> 
> [UPDATE][r4business][0.1.22]
> 
> 
> [UPDATE][r4business][0.1.22]update readme

- codeninja7bq4/README.md
- codeninja7bq4/TerminusManifest.yaml
- llama2chat7bq4/README.md
- llama2chat7bq4/TerminusManifest.yaml
- mistralins7bq4/README.md
- mistralins7bq4/TerminusManifest.yaml
- noromaid7b/README.md
- noromaid7b/TerminusManifest.yaml
- openchat7b/README.md
- openchat7b/TerminusManifest.yaml
- phi23b/README.md
- phi23b/TerminusManifest.yaml
- r4business/README.md
- r4entertainment/README.md
- r4sport/README.md
- r4tech/README.md
- r4tech/TerminusManifest.yaml
- r4techbiz/README.md
- r4techbiz/TerminusManifest.yaml
- r4world/TerminusManifest.yaml
- stealth7b/README.md
- stealth7b/TerminusManifest.yaml
- yarnmistral7b/README.md
- yarnmistral7b/TerminusManifest.yaml
> batch fix readme style

- bazarr/Chart.yaml
- bazarr/TerminusManifest.yaml
> [UPDATE][bazarr][0.0.5]bump version for test

- bazarr/Chart.yaml
- bazarr/TerminusManifest.yaml
- photoprism/Chart.yaml
- photoprism/TerminusManifest.yaml
- r4entertainment/Chart.yaml
- r4entertainment/TerminusManifest.yaml
- r4world/Chart.yaml
- r4world/TerminusManifest.yaml
> batch update version for doc screenshots

- novella/Chart.yaml
- novella/TerminusManifest.yaml
- novella/templates/deployment.yaml
novella
update OPENAI_BASE_URL
> [UPDATE][novella][0.0.12]update domain

- wordpress/Chart.yaml
- wordpress/TerminusManifest.yaml
- wordpress/templates/proxy.yaml
- wordpress/templates/wordpress.yaml
Wordpress
update image repo, improve initial robustness
> [UPDATE][wordpress][0.0.13] update image repo, improve initial robustness

- penpot/.helmignore
- penpot/Chart.yaml
- penpot/TerminusManifest.yaml
- penpot/owners
- penpot/templates/_helpers.tpl
- penpot/templates/backend/deployment.yaml
- penpot/templates/backend/service.yaml
- penpot/templates/exporter/deployment.yaml
- penpot/templates/exporter/service.yaml
- penpot/templates/frontend/deployment.yaml
- penpot/templates/frontend/service.yaml
- penpot/templates/redis/deployment.yaml
- penpot/templates/redis/service.yaml
- penpot/values.yaml
> penpot
> Penpot is the web-based open-source design tool that bridges
the gap between designers and developers.
> [NEW][penpot][0.0.1]add penpot

- nzbget/Chart.yaml
- nzbget/TerminusManifest.yaml
- nzbget/templates/deployment.yaml
> [UPDATE][nzbget][0.0.7]sync from prod repo

- r4entertainment0522/.helmignore
- r4entertainment0522/Chart.yaml
- r4entertainment0522/README.md
- r4entertainment0522/TerminusManifest.yaml
- r4entertainment0522/owners
- r4entertainment0522/templates/_helpers.tpl
- r4entertainment0522/templates/embedding.yaml
- r4entertainment0522/templates/prerank.yaml
- r4entertainment0522/templates/rank.yaml
- r4entertainment0522/templates/train.yaml
> [NEW][r4entertainment0522][0.1.26]create ent0522

- r4entertainment0522/Chart.yaml
- r4entertainment0522/TerminusManifest.yaml
> [UPDATE][r4entertainment0522][0.1.27]fix feedname

- r4business0522/Chart.yaml
- r4business0522/TerminusManifest.yaml
> 
> [UPDATE][r4business0522][0.1.25]
> 
> 
>
> [UPDATE][r4business0522][0.1.25]fix app name

- farcasterhubble/Chart.yaml
- farcasterhubble/README.md
- farcasterhubble/TerminusManifest.yaml
> [UPDATE][farcasterhubble][0.0.24]update info and add readme for test

- bytebase/Chart.yaml
- bytebase/README.md
- bytebase/TerminusManifest.yaml
> 
> [UPDATE][bytebase][0.0.9]
> 
> 
>
> [UPDATE][bytebase][0.0.9]docs: add readme

- bytebase/Chart.yaml
- bytebase/README.md
- bytebase/TerminusManifest.yaml
> [UPDATE][bytebase][0.0.10]  test md

- mongodb/Chart.yaml
- mongodb/TerminusManifest.yaml
> [UPDATE][mongodb][6.0.5]add onlyAdmin

- denny/Chart.yaml
- denny/TerminusManifest.yaml
> 
> [UPDATE][denny][0.0.2]
> 
> 
>
> [UPDATE][denny][0.0.2]add mobile support

- jellyfin/Chart.yaml
- jellyfin/TerminusManifest.yaml
> [UPDATE][jellyfin][0.0.6]add onlyAdmin

- mongodb/Chart.yaml
- mongodb/TerminusManifest.yaml
- mongodb/templates/deployment.yaml
> 
> [UPDATE][mongodb][6.0.4]
> 
> 
>
> [UPDATE][mongodb][6.0.6]deployment for multi node

- devbox/.helmignore
- devbox/Chart.yaml
- devbox/TerminusManifest.yaml
- devbox/owners
- devbox/templates/deployment.yaml
- devbox/values.yaml
> [NEW][devbox][0.0.1]add devbox

- r4test/.helmignore
- r4test/Chart.yaml
- r4test/README.md
- r4test/TerminusManifest.yaml
- r4test/owners
- r4test/templates/_helpers.tpl
- r4test/templates/embedding.yaml
- r4test/templates/prerank.yaml
- r4test/templates/rank.yaml
- r4test/templates/train.yaml
> [NEW][r4test][0.1.32]Add test recommend

- r4test/Chart.yaml
- r4test/TerminusManifest.yaml
- r4test/templates/rank.yaml
> [UPDATE][r4test][0.1.33]

- calendar/Chart.yaml
- calendar/TerminusManifest.yaml
- calendar/templates/calendar_deploy.yaml
> [UPDATE][calendar][0.0.4]

- r4test/Chart.yaml
- r4test/TerminusManifest.yaml
- r4test/templates/rank.yaml
> [UPDATE][r4test][0.1.34]

- devbox/Chart.yaml
- devbox/TerminusManifest.yaml
- devbox/owners
- devbox/templates/deployment.yaml
> [UPDATE][devbox][0.0.2]feat: upgrade to v0.1.28

- firefox/Chart.yaml
- firefox/TerminusManifest.yaml
> 
> [UPDATE][firefox][0.0.4]
> 
> 
>
> [UPDATE][firefox][0.0.4]bump version for test

- immich/Chart.yaml
- immich/TerminusManifest.yaml
- immich/owners
- immich/templates/deployment.yaml
> [NEW][immich][0.0.1]add immich placeholder

- appsmith/Chart.yaml
- appsmith/TerminusManifest.yaml
- appsmith/owners
- appsmith/templates/deployment.yaml
- mattermost/Chart.yaml
- mattermost/TerminusManifest.yaml
- mattermost/owners
- mattermost/templates/deployment.yaml
- memos/Chart.yaml
- memos/TerminusManifest.yaml
- memos/owners
- memos/templates/deployment.yaml
- odoo/Chart.yaml
- odoo/TerminusManifest.yaml
- odoo/owners
- odoo/templates/deployment.yaml
- paperless/Chart.yaml
- paperless/TerminusManifest.yaml
- paperless/owners
- paperless/templates/deployment.yaml
- rocketchat/Chart.yaml
- rocketchat/TerminusManifest.yaml
- rocketchat/owners
- rocketchat/templates/deployment.yaml
- supabase/Chart.yaml
- supabase/TerminusManifest.yaml
- supabase/owners
- supabase/templates/deployment.yaml
> batch add app placeholder

- r4techbiz/Chart.yaml
- r4techbiz/TerminusManifest.yaml
- r4techbiz/owners
- r4world/Chart.yaml
- r4world/TerminusManifest.yaml
- r4world/owners
> bump version for test

- difyfusionclient/Chart.yaml
- difyfusionclient/TerminusManifest.yaml
- difyfusionclient/templates/dify_fe_deploy.yaml
> 
> [UPDATE][difyfusionclient][0.0.2]
> 
> 
>
> [UPDATE][difyfusionclient][0.0.2]fix: auto connect

- prowlarr/TerminusManifest.yaml
- prowlarr/templates/deployment.yaml
- sonarr/TerminusManifest.yaml
- sonarr/templates/deployment.yaml
> test legacy api: add provider register and permission

- prowlarr/templates/deployment.yaml
- sonarr/templates/deployment.yaml
> Test legacy api

- prowlarr/Chart.yaml
- prowlarr/TerminusManifest.yaml
- prowlarr/templates/deployment.yaml
- sonarr/Chart.yaml
- sonarr/TerminusManifest.yaml
- sonarr/templates/deployment.yaml
> fix: datatype and endpoint

- transmission/Chart.yaml
- transmission/TerminusManifest.yaml
- transmission/templates/deployment.yaml
> [UPDATE][transmission][0.0.4]fix provider and add arm64 tag test2

- komga/Chart.yaml
- komga/TerminusManifest.yaml
- komga/owners
- komga/templates/deployment.yaml
- mongo/Chart.yaml
- mongo/TerminusManifest.yaml
- mongo/owners
- mongo/templates/deployment.yaml
- ollama/Chart.yaml
- ollama/TerminusManifest.yaml
- ollama/owners
- ollama/templates/deployment.yaml
- perplexica/Chart.yaml
- perplexica/TerminusManifest.yaml
- perplexica/owners
- perplexica/templates/deployment.yaml
- searxng/Chart.yaml
- searxng/TerminusManifest.yaml
- searxng/owners
- searxng/templates/deployment.yaml
> batch add placeholder apps

- dendrite/Chart.yaml
- dendrite/TerminusManifest.yaml
- dendrite/owners
- dendrite/templates/Deployment.yaml
- dendrite/templates/Job.yaml
- dendrite/templates/RBAC.yaml
- dendrite/templates/Secret.yaml
- dendrite/templates/Service.yaml
- dendrite/templates/Web-Cinny.yaml
- dendrite/templates/Web-Element.yaml
- dendrite/templates/Web-Fluffychat.yaml
- dendrite/templates/Web-Hydrogen.yaml
> [NEW][dendrite][0.0.10]new app dendrite

- gaianet/.helmignore
- gaianet/Chart.yaml
- gaianet/TerminusManifest.yaml
- gaianet/owners
- gaianet/templates/deployment.yaml
- gaianet/values.yaml
> [NEW][gaianet][0.0.1]
> 
> 
> 
>
> [NEW][gaianet][0.0.1]Add GaiaNet placeholder

- r4cntest/Chart.yaml
> fix r4cntest chart name

- r4cntest/Chart.yaml
- r4cntest/TerminusManifest.yaml
- r4cntest/templates/embedding.yaml
> [UPDATE][r4cntest][0.1.38]fix user embedding

- r4test/Chart.yaml
- r4test/TerminusManifest.yaml
- r4test/templates/embedding.yaml
- r4test/templates/prerank.yaml
- r4test/templates/rank.yaml
- r4test/templates/train.yaml
> 
> [UPDATE][r4test][0.1.35]
> 
> 
>
> [UPDATE][r4test][0.1.35]feat: upgrade images

- r4cntest/Chart.yaml
- r4cntest/TerminusManifest.yaml
- r4cntest/templates/embedding.yaml
- r4cntest/templates/prerank.yaml
> 
> [UPDATE][r4cntest][0.1.39]
> 
> 
>
> [UPDATE][r4cntest][0.1.39]fix prerank sync model

- firefox/Chart.yaml
- firefox/TerminusManifest.yaml
- firefox/i18n/en/TerminusManifest.yaml
- firefox/i18n/zh/TerminusManifest.yaml
- firefox/templates/firefox.yaml
> 
> [UPDATE][firefox][0.0.5]add i18n
> 
> 
>
> [UPDATE][firefox][0.0.5]add i18n

- .idea/.gitignore
- .idea/modules.xml
- .idea/terminus-apps.iml
- .idea/vcs.xml
- firefox/Chart.yaml
- firefox/TerminusManifest.yaml
> [UPDATE][firefox][0.0.6]update version

- firefox/i18n/en/TerminusManifest.yaml
- firefox/i18n/zh/TerminusManifest.yaml
> [UPDATE][firefox][0.0.6]update i18n

- prometheus/.helmignore
- prometheus/Chart.yaml
- prometheus/TerminusManifest.yaml
- prometheus/owners
- prometheus/templates/_helpers.tpl
- prometheus/templates/deployment.yaml
- prometheus/values.yaml
> [NEW][prometheus][0.0.3]add placeholder
> 
> 
> 
>
> [NEW][prometheus][0.0.3]add placeholder

- affine/Chart.yaml
- affine/TerminusManifest.yaml
- affine/i18n/zh-CN/TerminusManifest.yaml
- affine/owners
> 
> [UPDATE][affine][0.0.11]
> 
> 
>
> [UPDATE][affine][0.0.11]i18n test

- affine/i18n/zh-CN/TerminusManifest.yaml
> [UPDATE][affine][version]test

- ollama/Chart.yaml
- ollama/OlaresManifest.yaml
- ollama/templates/deployment.yaml
> [UPDATE][ollama][1.0.2]rm gpu config

- openwebui/Chart.yaml
- openwebui/OlaresManifest.yaml
- openwebui/templates/deployment.yaml
> [UPDATE][openwebui][1.0.2]support arm

- openwebui/Chart.yaml
- openwebui/OlaresManifest.yaml
> openwebui
> config olares version
> [UPDATE][openwebui][1.0.3]config olares version

- ollama/Chart.yaml
- ollama/OlaresManifest.yaml
> ollama
> test save old version
> [UPDATE][ollama][1.0.4]test save old version

- r4business/templates/embedding.yaml
- r4business/templates/train.yaml
- r4cnall/templates/embedding.yaml
- r4cnall/templates/train.yaml
- r4cntest/templates/embedding.yaml
- r4cntest/templates/train.yaml
- r4entertainment/templates/embedding.yaml
- r4entertainment/templates/train.yaml
- r4sport/templates/embedding.yaml
- r4sport/templates/train.yaml
- r4tech/templates/embedding.yaml
- r4tech/templates/train.yaml
- r4techbiz/templates/embedding.yaml
- r4techbiz/templates/train.yaml
- r4wechat/templates/embedding.yaml
- r4wechat/templates/train.yaml
- r4world/templates/embedding.yaml
- r4world/templates/train.yaml
> r4 schedule

- r4wechat/Chart.yaml
- r4wechat/OlaresManifest.yaml
> 
> [UPDATE][r4wechat][1.0.3]
> 
> 
>
>  [UPDATE][r4wechat][1.0.3]bump version to update

- r4wechat/Chart.yaml
- r4wechat/OlaresManifest.yaml
- r4wechat/templates/rank.yaml
- r4wechat/templates/train.yaml
> 
> [UPDATE][r4wechat][1.0.4]
> 
> 
>
> [UPDATE][r4wechat][1.0.4]

- gitlabfusionclient/Chart.yaml
- gitlabfusionclient/OlaresManifest.yaml
> 
> [UPDATE][gitlabfusionclient][0.0.29]add mandatory
> 
> 
>
> [UPDATE][gitlabfusionclient][0.0.29]add mandatory

- comfyui/Chart.yaml
- comfyui/OlaresManifest.yaml
- comfyui/i18n/en-US/OlaresManifest.yaml
- comfyui/i18n/zh-CN/OlaresManifest.yaml
- comfyui/templates/configmap.yaml
- comfyui/templates/deployment.yaml
> 
> [UPDATE][comfyui][1.0.15]
> 
> 
>
> [UPDATE][comfyui][1.0.15]fix: comfyui to 1.0.15

- n8n/Chart.yaml
- n8n/OlaresManifest.yaml
> [UPDATE][n8n][0.1.0]test new git pull

- firefox/Chart.yaml
- firefox/OlaresManifest.yaml
> [UPDATE][firefox][0.0.5]feat: test update

- firefox/Chart.yaml
- firefox/OlaresManifest.yaml
> [UPDATE][firefox][0.0.6]feat: test update

- firefox/Chart.yaml
- firefox/OlaresManifest.yaml
> [UPDATE][firefox][1.0.2]feat: test update

- dify/Chart.yaml
- dify/OlaresManifest.yaml
- dify/templates/server/api/api-deployment.yaml
- dify/templates/server/plugin/plugin-daemon-deployment.yaml
- dify/templates/server/sandbox/sandbox-deployment.yaml
- dify/templates/server/web-deployment.yaml
- dify/templates/server/worker/worker-deployment.yaml
> [UPDATE][dify][1.1.13] add conflicts and try 1.1.3 version

- r4business/Chart.yaml
- r4business/OlaresManifest.yaml
- r4business/templates/embedding.yaml
- r4business/templates/prerank.yaml
- r4business/templates/rank.yaml
- r4business/templates/train.yaml
> [UPDATE][r4business][0.0.28]

- astral/Chart.yaml
- astral/OlaresManifest.yaml
> [UPDATE][astral][1.0.4]Test update app 

- astral/Chart.yaml
- astral/OlaresManifest.yaml
> [UPDATE][astral][1.0.5]Test update app

- studio/Chart.yaml
- studio/OlaresManifest.yaml
> 
> [UPDATE][studio][1.0.8]bump version for test
> 
> 
>
> [UPDATE][studio][1.0.8]bump version for test

- wise/Chart.yaml
- wise/OlaresManifest.yaml
- wise/knowledge/Chart.yaml
- wise/knowledge/templates/knowledge_deployment.yaml
- wise/owners
- wise/wise/Chart.yaml
- wise/wise/templates/front.yaml
> [UPDATE][wise][1.0.20]fix 3in1 bugs

- openedaispeech/Chart.yaml
- openedaispeech/OlaresManifest.yaml
- openedaispeech/templates/deployment.yaml
openedaispeech
feat: change to rbac provider
> [UPDATE][openedaispeech][1.0.5]feat: change to rbac provider

- sonarr/Chart.yaml
- sonarr/OlaresManifest.yaml
- sonarr/templates/deployment.yaml
sonarr
feat: change to rbac provider
> [UPDATE][sonarr][1.0.4]feat: change to rbac provider

- qbittorrent/Chart.yaml
- qbittorrent/OlaresManifest.yaml
- qbittorrent/templates/deployment.yaml
> 
> [UPDATE][qbittorrent][1.0.3]feat: change to rbac provider
> 
> 
>
> [UPDATE][qbittorrent][1.0.3]feat: change to rbac provider

- radarr/Chart.yaml
- radarr/OlaresManifest.yaml
- radarr/templates/deployment.yaml
> 
> [UPDATE][radarr][1.0.2]feat: change to rbac provider
> 
> 
>
>  [UPDATE][radarr][1.0.2]feat: change to rbac provider

- deluge/Chart.yaml
- deluge/OlaresManifest.yaml
- deluge/templates/deployment.yaml
> [UPDATE][deluge][1.0.3]feat: change to rbac provider

- bazarr/Chart.yaml
- bazarr/OlaresManifest.yaml
- bazarr/templates/deployment.yaml
> 
> [UPDATE][bazarr][1.0.4]change to rbac provider
> 
> 
>
> [UPDATE][bazarr][1.0.4]change to rbac provider

- nzbget/Chart.yaml
- nzbget/OlaresManifest.yaml
- nzbget/templates/deployment.yaml
> 
> [UPDATE][nzbget][1.0.3]feat: change to rbac provider
> 
> 
>
> [UPDATE][nzbget][1.0.3]feat: change to rbac provider

- transmission/Chart.yaml
- transmission/OlaresManifest.yaml
- transmission/templates/deployment.yaml
transmission
feat: change to rbac provider
> [UPDATE][transmission][1.0.4]feat: change to rbac provider

- sickchill/Chart.yaml
- sickchill/OlaresManifest.yaml
- sickchill/templates/deployment.yaml
sickchill
feat: change to rbac provider
> [UPDATE][sickchill][1.0.5]feat: change to rbac provider

- homeassistant/Chart.yaml
- homeassistant/OlaresManifest.yaml
- homeassistant/templates/deployment.yaml
auto merge
> 
> [UPDATE][homeassistant][1.0.7]
> 
> 
>
> [UPDATE][homeassistant][1.0.7]upgrade version 2025.8.3 add supportArch arm64 (#1019)

- blinko/Chart.yaml
- blinko/OlaresManifest.yaml
> 
> [UPDATE][blinko][1.0.3]change provider to rbac
> 
> 
>
> [UPDATE][blinko][1.0.3]change provider to rbac

- chinesesubfinder/Chart.yaml
- chinesesubfinder/OlaresManifest.yaml
- chinesesubfinder/templates/chinesesubfinder.yaml
> [UPDATE][chinesesubfinder][1.0.4]change provider to rbac

- deerflow/Chart.yaml
- deerflow/OlaresManifest.yaml
> [UPDATE][deerflow][1.0.5]change provider to rbac

- sdwebuiforgeshare/Chart.yaml
- sdwebuiforgeshare/OlaresManifest.yaml
- sdwebuiforgeshare/templates/deployment.yaml
> [UPDATE][sdwebuiforgeshare][1.0.7]change provider to rbac

- refly/Chart.yaml
- refly/OlaresManifest.yaml
> [UPDATE][refly][1.0.2]change provider to rbac

- ragflow/Chart.yaml
- ragflow/OlaresManifest.yaml
> [UPDATE][ragflow][1.0.10]change provider to rbac

- pdfmathtranslate/Chart.yaml
- pdfmathtranslate/OlaresManifest.yaml
> [UPDATE][pdfmathtranslate][1.0.5]change provider to rbac

- ollamaqwen314b/Chart.yaml
- ollamaqwen314b/OlaresManifest.yaml
- ollamaqwen314b/i18n/en-US/OlaresManifest.yaml
- ollamaqwen314b/i18n/zh-CN/OlaresManifest.yaml
- ollamaqwen314b/owners
- ollamaqwen314b/templates/clientproxy.yaml
- ollamaqwen314b/templates/deployment.yaml
ollamaqwen314b
ollama for qwen3:14b
> [NEW][ollamaqwen314b][1.1.5]add app ollamaqwen314b

- jaaz/Chart.yaml
- jaaz/OlaresManifest.yaml
- jaaz/templates/deployment.yaml
> [UPDATE][jaaz][1.0.6] update provider

- firefox/Chart.yaml
- firefox/OlaresManifest.yaml
- firefox/price.yaml
> [UPDATE][firefox][1.0.5]test account

- firefox/Chart.yaml
- firefox/OlaresManifest.yaml
- firefox/price.yaml
> [UPDATE][firefox][1.0.6]test check

- ollamacogito14b/Chart.yaml
- ollamacogito14b/OlaresManifest.yaml
> 
> [UPDATE][ollamacogito14b][1.1.6]
> 
> 
>
> [UPDATE][ollamacogito14b][1.1.6]

- ollamadeepseekr114b/Chart.yaml
- ollamadeepseekr114b/OlaresManifest.yaml
> 
> [UPDATE][ollamadeepseekr114b][1.1.7]
> 
> 
>
> [UPDATE][ollamadeepseekr114b][1.1.7]

- ollamaminicpmv8b/Chart.yaml
- ollamaminicpmv8b/OlaresManifest.yaml
> 
> [UPDATE][ollamaminicpmv8b][1.1.6]
> 
> 
>
> [UPDATE][ollamaminicpmv8b][1.1.6]

- ollamaphi414b/Chart.yaml
- ollamaphi414b/OlaresManifest.yaml
> 
> [UPDATE][ollamaphi414b][1.1.6]
> 
> 
>
> [UPDATE][ollamaphi414b][1.1.6]

- ollamaqwen314b/Chart.yaml
- ollamaqwen314b/OlaresManifest.yaml
> 
> [UPDATE][ollamaqwen314b][1.1.9]
> 
> 
>
> [UPDATE][ollamaqwen314b][1.1.9]

- merchant/Chart.yaml
- merchant/OlaresManifest.yaml
- merchant/templates/deployment.yaml
- merchant/templates/vc-gateway.yaml
- merchant/templates/vc-system.yaml
- merchant/values.yaml
> merchant
> Developer application used for paid app feature development
> [UPDATE][merchant][0.3.17]update version

- perplexica/Chart.yaml
- perplexica/OlaresManifest.yaml
- perplexica/templates/1-10-2/deployment.yaml
- 0abba230: fix bug (#1068) (by Harvey)
- 2c822344: [UPDATE][ollama][1.1.9] (#1029) (by Teng)
同步了 2 个提交。
> sync from prod 2025-09-22

- ollamallama318b/Chart.yaml
- ollamallama318b/OlaresManifest.yaml
- ollamallama318b/i18n/en-US/OlaresManifest.yaml
- ollamallama318b/i18n/zh-CN/OlaresManifest.yaml
- ollamallama318b/owners
- ollamallama318b/templates/clientproxy.yaml
- ollamallama318b/templates/deployment.yaml
> [NEW][ollamallama318b][1.1.5]add app ollamallama3.1_8b

- firefox/Chart.yaml
- firefox/OlaresManifest.yaml
- firefox/price.yaml
> [UPDATE][firefox][1.0.8]test account

- bisheng/Chart.yaml
- bisheng/OlaresManifest.yaml
- bisheng/templates/deployment.yaml
- comfyuishare/Chart.yaml
- comfyuishare/OlaresManifest.yaml
- comfyuishare/i18n/en-US/OlaresManifest.yaml
- comfyuishare/i18n/zh-CN/OlaresManifest.yaml
- comfyuishare/templates/deployment.yaml
- studio/Chart.yaml
- studio/OlaresManifest.yaml
- studio/studio/Chart.yaml
- studio/studioserver/Chart.yaml
- bdf590a1: [UPDATE][bisheng][1.0.4]update image upgrade version 2.1.1 (#1074) (by Harvey)
- 0836d0cb: [UPDATE][comfyuishare][1.2.22]fix description (#1073) (by Teng)
- b26e2f12: [UPDATE][comfyuishare][1.2.21]update to 0.3.60 (#1071) (by Teng)
- d5225217: add studio (#1072) (by Teng)
同步了 4 个提交。
> sync from prod 2025-09-30
